# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: blog
  pool: 5
  username: root
  password: test
  host: localhost
  port: 3306