# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4021e3cd26e84df7c57d72d46a9b5594ae6bf495160e95e5a61d269b613cfa0edf712550d351387478786a5d5801ce5a5d45e672282a1eddd7dc5525e856766

test:
  secret_key_base: c8ca325ff0e28568921fa23a4ee57d422d098da3bf12c1eb82fd60781bd1db5a8f72b015e5930f449737441f06fd720abf4d9109b58f45f8412de1d249e59053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
